### ISSUE TITLE
docker-compose AssertionError mount path

### ISSUE THREAD

**Issue by dabm-git** [BaldissaraMatheus/Tasks.md#26]
Used: https://github.com/BaldissaraMatheus/Tasks.md/blob/main/examples/docker-compose.yaml

```
node:assert:124
  throw new AssertionError(obj);
  ^
AssertionError [ERR_ASSERTION]: mount path must begin with "/"
    at mount (/api/node_modules/koa-mount/index.js:33:10)
    at Object.<anonymous> (/api/server.js:159:9)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: '"',
  expected: '/',
  operator: '=='
}
Node.js v18.14.2
```

This error message is indicating that there is a problem with the mount path used in the koa-mount module. The error message is indicating that the mount path provided to the mount function must begin with a forward slash (/), but the actual value provided does not meet this requirement.

**Comment by sergioponguta** [comment]
Same error here. Any solution? Or working example of dockercompose?

**Comment by BaldissaraMatheus** [comment]
I'll be closing this for now since it was supposedly fixed, but if you verify that it's still not working feel free to open it again
